import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/app-sidebar';

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <SidebarProvider>
          <AppSidebar />
          <main className="w-full flex flex-col">
            <div className="border-b py-2.5 bg-white">
              <SidebarTrigger />
            </div>
            <div className="bg-[#F4F5F7] grow">
              <div>{children}</div>
            </div>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
